apiVersion: apps/v1
kind: Deployment
metadata: 
  name: star-wars-deployment
spec:
  selector:
    matchLabels:
      app: star-wars
  replicas: 3
  template:
    metadata:
      labels:
        app: star-wars
    spec:
      containers:
      - name: star-wars
        image: gabrielborc/star-wars-api
        ports: 
        - containerPort: 9000